spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SHOES_STORE_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

vnp.tmn.code=JRPU06NQ
vnp.hash.secret=3BLF2X06DA3DV5P9DR2DB7P36ECI8O5N
vnp.pay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.return.url=http://localhost:5173/admin/pos-management